// Copyright (c) 2026 Argilette Lab. SPDX-License-Identifier: MIT
import { Link } from "wouter";
import { ArrowLeft, Sparkles } from "lucide-react";

export default function TermsPage() {
  return (
    <main className="mx-auto min-h-screen max-w-2xl px-6 py-12">
      <header className="mb-10 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2 text-lg font-semibold">
          <Sparkles className="h-5 w-5 text-primary" /> Zola
        </Link>
        <Link href="/" className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground">
          <ArrowLeft className="h-4 w-4" /> Back
        </Link>
      </header>
      <article className="prose prose-invert max-w-none">
        <h1>Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: July 3, 2026</p>
        <p>
          By using Zola (the "Service"), operated by Argilette Lab ("we," "us," or "our"), you agree to
          these Terms of Service. If you do not agree, do not use the Service.
        </p>
        <h2>1. Use of the Service</h2>
        <p>
          You may use Zola for lawful purposes only. You must not use the Service to generate malicious
          code, violate third-party rights, or circumvent AI provider usage policies.
        </p>
        <h2>2. Accounts</h2>
        <p>
          You are responsible for maintaining the security of your account. Notify us immediately at{" "}
          <a href="mailto:hello@argilette.com">hello@argilette.com</a> if you suspect unauthorized use.
        </p>
        <h2>3. AI-generated content</h2>
        <p>
          Code and content generated by the AI models within Zola is provided as-is. We make no
          guarantees about correctness, security, or fitness for any particular purpose.
        </p>
        <h2>4. Payments</h2>
        <p>
          Paid plans are billed monthly. You may cancel at any time through the billing portal. No
          refunds are issued for partial months.
        </p>
        <h2>5. Termination</h2>
        <p>
          We reserve the right to suspend or terminate accounts that violate these terms.
        </p>
        <h2>6. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, Argilette Lab is not liable for any indirect,
          incidental, or consequential damages arising from use of the Service.
        </p>
        <h2>7. Changes</h2>
        <p>
          We may update these terms at any time. Continued use after changes constitutes acceptance.
        </p>
      </article>
    </main>
  );
}
